export const SHOW_REQUEST_LOADING = 'SHOW_REQUEST_LOADING';
export const AUTH_PERMISSION_REQUEST = 'AUTH_PERMISSION_REQUEST';
export const AUTH_REQUEST_SUCCESS = 'AUTH_REQUEST_SUCCESS';
export const AUTH_REQUEST_FAILED = 'AUTH_REQUEST_FAILED';
export const HIDE_REQUEST_LOADING = 'HIDE_REQUEST_LOADING';
export const SELECT_ROLE = 'SELECT_ROLE';
export const SELECT_USER = 'SELECT_USER';
